//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ABSpriteEditor.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class WarningStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal WarningStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ABSpriteEditor.Properties.WarningStrings", typeof(WarningStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The sprite file &quot;{0}&quot; has recent changes that have not been saved. Do you want to save these changes before closing?.
        /// </summary>
        internal static string ClosingUnsavedSprite {
            get {
                return ResourceManager.GetString("ClosingUnsavedSprite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The sprite frame and any frames that follow it will be overwritten with the contents of the dropped images..
        /// </summary>
        internal static string FileDropOverwritesFrames {
            get {
                return ResourceManager.GetString("FileDropOverwritesFrames", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The namespace name provided is invalid and will be changed to the following: &quot;{0}&quot;..
        /// </summary>
        internal static string InvalidNamespaceNameChanged {
            get {
                return ResourceManager.GetString("InvalidNamespaceNameChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The sprite name provided is invalid and will be changed to the following: &quot;{0}&quot;..
        /// </summary>
        internal static string InvalidSpriteNameChanged {
            get {
                return ResourceManager.GetString("InvalidSpriteNameChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The created sprite will exceed the Arduboy&apos;s memory limit. The sprite would require {0} bytes of memory, the Arduboy only has {1}..
        /// </summary>
        internal static string SpriteExceedsArduboyMemoryLimit {
            get {
                return ResourceManager.GetString("SpriteExceedsArduboyMemoryLimit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The generated header file will violate the ODR and thus be unable to compile. Please make sure that sprites and namespaces within the same namespace have unique names..
        /// </summary>
        internal static string SpriteFileViolatesTheODR {
            get {
                return ResourceManager.GetString("SpriteFileViolatesTheODR", resourceCulture);
            }
        }
    }
}
